### ISSUE TITLE
postcss 8 support ?

### ISSUE THREAD

**Issue by anikethsaha** [Siilwyn/css-declaration-sorter#106]
Hi, 

We are using this plugin in `cssnano`'s default preset [here](https://github.com/cssnano/cssnano/blob/master/packages/cssnano-preset-default/src/index.js#L15) and as well as in our advance preset (though default)
As we are migrating to postcss 8 https://github.com/cssnano/cssnano/pull/954, support for postcss 8 in this plugin might be a blocker for us. 
Do you have any plan to support `postcss 8` ? I can make a PR (by simply following the official migration guide) but as I am not familiar with the internal functionality of this plugin I think I might not be the best person do so. 

Let me know if there is any consideration for this.

**Comment by Siilwyn** [comment]
Hi @anikethsaha, thank you for your question, I wasn't aware of PostCSS 8. Definitely going to migrate.

**Comment by anikethsaha** [comment]
Thanks a lot

**Comment by Siilwyn** [comment]
@anikethsaha will the new `cssnano` upgrade drop Node.js version support?

Since this is a major change (new `postcss` peer dependency) for `css-declaration-sorter` I'd like to drop Node.js 10 support so I can fix #50. Because Node.js 10 reaches EOL at 2021-04 this would be good to do in one major version bump: I don't like publishing two major version bumps in a short timespan.

If you want to continue support to support Node.js 10 I could also publish a new version under the `next` tag on npm so you can use that temporarily.

css-declaration-sorter

**Comment by anikethsaha** [comment]
Currently, we haven't discussed that. 

I think I would like to support the node version which is being supported by postcss (as first thought.) but we can differentiate with it. 

cc @evilebottnawi

**Comment by evilebottnawi** [comment]
@Siilwyn Unfortunately, then we will have to turn off this plugin or transfer the code to our repo, postcss output warnings on old plugin syntax, so it will be very annoying, what is the problem to have 2 major releases? The numbers are endless and never end :smile:

**Comment by Siilwyn** [comment]
@evilebottnawi having two major version bumps causes a lot of people using the package having to do a major version upgrade twice. What do you think of using the package under a next tag? (`css-declaration-sorter@next`)

**Comment by evilebottnawi** [comment]
@Siilwyn 

> What do you think of using the package under a next tag? (css-declaration-sorter@next)

Sounds good

> having two major version bumps causes a lot of people using the package having to do a major version upgrade twice.

Why do you need two major versions? PostCSS@8 migration is started, so you will get more issues about this in near future, I think it is good idea to do it right now

**Comment by Siilwyn** [comment]
It's already done btw :eyes: https://github.com/Siilwyn/css-declaration-sorter/commit/e74c93d0eb4ac94c70651040b1c0bfeea5586b2c

But I just don't want to bother every user/developer with two major version bumps, just a waste of time for most. Will go with the `next` tag!

**Comment by evilebottnawi** [comment]
I think using `Root` is wrong here, I think better to use `Once`

/cc @ai

**Comment by ai** [comment]
Maybe `OnceExit` is better since we want to sort properties after all transformations

**Comment by Siilwyn** [comment]
Ah thanks for the feedback, will look into using `OnceExit`.

**Comment by Siilwyn** [comment]
Sadly I can't get either `Once` or `OnceExit` to work, `Root` seems to work perfectly in the tests however. Will it mess up in combination with other plugins?

**Comment by ai** [comment]
`Root` is semantically correct as well.

`OnceExit` is just an performance optimization. But it could have conflict with other plugins with `OnceExit` AST changes.

**Comment by Siilwyn** [comment]
Actually updated from `postcss@8.0.9` to `postcss@8.1.1`, now using `OnceExit` works like a charm.

**Comment by Siilwyn** [comment]
`css-declaration-sorter@next` is out! :package:
