### ISSUE TITLE
ERROR: no such file or directory, open 'orders/smacss.json'

### ISSUE THREAD

**Issue by alexanderTUR** [Siilwyn/css-declaration-sorter#117]
I have updated all dependencies to lastest version, and now I got an error:

```
[20:25:42] Error in plugin "gulp-postcss"
Message:
    ENOENT: no such file or directory, open 'orders/smacss.json'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: orders/smacss.json
    fileName: /Users/alextur/Work/gulp-start-template/src/sass/main.css
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: ENOENT: no such file or directory, open 'orders/smacss.json'
```

Plugins versions:
```
    "css-declaration-sorter": "^6.0.1",
    "gulp-postcss": "^9.0.0",
    "postcss": "^8.1.4"
```

Before the update everything was OK. I reinstalled all dependencies, tried to delete .lock file - no result.

Any ideas, what I am doing wrong?

To see all code you can go to my [GULP start temlate](https://github.com/alexanderTUR/gulp-start-template) and find `gulp/tasks/sass.js`, there you will find commented usage of this plugin at line 79. If you install all dependencies, uncomment this line, and trying to run `gulp` - you will get that error.

**Comment by Siilwyn** [comment]
Good catch, thank you! This is caused by a mistake I made when changing the source from CommonJS to ESM.
Version `css-declaration-sorter@6.0.2` should fix this, please let me know if you bump into anything.

**Comment by alexanderTUR** [comment]
Thanks for the quick fix! Now everything works! )
