### ISSUE TITLE
Make css-declaration-sorter run in browser

### ISSUE THREAD

**Issue by ludofischer** [Siilwyn/css-declaration-sorter#172]
In order to create a complete online playground for cssnano (as requested in https://github.com/cssnano/cssnano/issues/1162), I would need to run css-declaration-sorter in thr browser.

I propose converting the JSON to a module exporting an array. 

Last time I've checked it was not possible because it uses `fs.readFile` to read a JSON file which contains the order:

https://github.com/Siilwyn/css-declaration-sorter/blob/bd5d7563355a2dd89e5c6e986ce4328b0e9f14d3/src/main.mjs#L36

But `fs.readFile` will not work in the browser. That would also require adapting [property-scraper.mjs](https://github.com/Siilwyn/css-declaration-sorter/blob/master/src/property-scraper.mjs). Using `import` with a JSON file works with a bundler but would need an experimental flag to run it in Node.js.

**Comment by Siilwyn** [comment]
Sounds do-able & like a good idea, I'll look into this!

**Comment by Siilwyn** [comment]
@ludofischer would a dynamic import, like `import(order)` work?

**Comment by ludofischer** [comment]
> @ludofischer would a dynamic import, like `import(order)` work?

I think it would work for bundlers.
