### ISSUE TITLE
Add TypeScript types?

### ISSUE THREAD

**Issue by Siilwyn** [Siilwyn/css-declaration-sorter#200]
```
function compare(a: string, b: string): -1 | 0 | 1 {
  return a === b ? 0 : a > b ? 1 : -1;
}
```

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

Shoutout & ask author of https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/css-declaration-sorter

**Comment by Siilwyn** [comment]
@peterblazejewicz :wave: 

I'm thinking of adding TS types directly in this package, what do you think?

**Comment by peterblazejewicz** [comment]
Hey, sure. Just start from a copy of current DT package declarations, update `package.json` here and make sure `.d.ts` types get published to NPM:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
this is a quick path, e.g. done by Sindre Sorhus' packages, e..g:
https://github.com/sindresorhus/file-type
https://github.com/sindresorhus/file-type/blob/main/package.json

**Comment by Siilwyn** [comment]
Alright thanks, that sounds straightforward! :)
