### ISSUE TITLE
How to use with .less/.scss when using the CLI?

### ISSUE THREAD

**Issue by madskristensen** [Siilwyn/css-declaration-sorter#24]
First of all, thanks for a great tool!!

I can't find out how to use the `cssdeclsort` CLI command for .less/.scss files. It works great for .css files, but even when I install `postcss-less` I can't make the CLI pick it up. Any ideas?

**Comment by Siilwyn** [comment]
Hi there @madskristensen you're probably after this: https://github.com/Siilwyn/css-declaration-sorter/issues/21

`postcss --use css-declaration-sorter --syntax postcss-scss src/theme/**/*.scss`

Please let me know how it goes. :)

**Comment by madskristensen** [comment]
Thanks, that was helpful. I can't seem to set the value on the `--order` argument. Here's what I do:

`postcss --use css-declaration-sorter --css-declaration-sorter.order smacss --syntax postcss-less test.less`

No matter what it always uses the default alphabetical sorting. Any ideas?

**Comment by Siilwyn** [comment]
Looking at the [`postcss-cli`](https://github.com/postcss/postcss-cli) documentation it seems like passing options is not possible without a configuration file. So you would need to add the config to a new file or the `package.json`.

package.json
```json
{
  "postcss": {
    "parser": "postcss-less",
    "plugins": {
      "css-declaration-sorter": { "order": "smacss" }
    }
  }
}
```

.postcssrc.js
```js
module.exports = {
  parser: 'postcss-less',
  plugins: [
    require('css-declaration-sorter')({ order: 'smacss' }),
  ]
}
```

And run the command:
`postcss test.less`

**Comment by madskristensen** [comment]
Thanks. Just what I needed
