### ISSUE TITLE
bubble-sort.mjs not published with package, breaks ESM import

### ISSUE THREAD

**Issue by amiller-gh** [Siilwyn/css-declaration-sorter#327]
As described! It appears in at least 6.4.0, and 7.0.0, `bubble-sort.mjs` is missing from the published `src` folder, despite being imported by `src/main.mjs`.

**Comment by Siilwyn** [comment]
Fixed in 6.4.1 and 7.0.2 (7.0.1 publish failed because of an invalid tag)
