### ISSUE TITLE
engine version conflict

### ISSUE THREAD

**Issue by WDD-Marv** [Siilwyn/css-declaration-sorter#59]
We've got node v10.3.0 running here, can't install css-declaration-sorter 4.0.0 due to the engine constraint in package.json :s

**Comment by Siilwyn** [comment]
Sorry about that, the engines value is totally wrong. Thank you for letting me know!

**Comment by Siilwyn** [comment]
Fixed with version `4.0.1`!

**Comment by WDD-Marv** [comment]
no worries :)
