### ISSUE TITLE
Support nested rules

### ISSUE THREAD

**Issue by Siilwyn** [Siilwyn/css-declaration-sorter#6]
Nested rules might be a reality in the next CSS specification release, on top of that almost all CSS preprocessors enable it and so does [postcss-nesting](https://github.com/jonathantneal/postcss-nesting).

Things to investigate before implementing this:
- How does this affect the speed of the module?
- How to handle newlines before and after nested selectors?

**Comment by cristian-sima** [comment]
+1

**Comment by pdrazewski** [comment]
+ 1

**Comment by Siilwyn** [comment]
I'm proud to say the module now supports nested rules as of 5f19e19. This also means Less and SCSS are supported! :tada: 

If you find this useful please consider retweeting my announcement:
https://twitter.com/Siilwyn/status/761565830010331136
