### ISSUE TITLE
Could we add support for Vue file?

### ISSUE THREAD

**Issue by NE-SmallTown** [Siilwyn/css-declaration-sorter#62]
I test but seems this can't process the *.vue file

**Comment by Siilwyn** [comment]
Hi there, excuse me for the late reply. Going to look into this! This falls into my plan of adding more documentation and examples how the sorter fits into the developer workflow.

**Comment by Siilwyn** [comment]
:wave: I've made a Prettier plugin to achieve this: https://github.com/Siilwyn/prettier-plugin-css-order

There is probably a way to do this with purely a Vue template file parser and this package, if somebody has a nice setup feel free to share and/or shoot a PR to include in the examples. Cheers!
