### ISSUE TITLE
Allow `order` option to be function

### ISSUE THREAD

**Issue by evilebottnawi** [Siilwyn/css-declaration-sorter#64]
Require to solve https://github.com/cssnano/cssnano/issues/535, we should avoid to sort `shorthand` properties if long property will be defined above. Can we implement this asap?

**Comment by Siilwyn** [comment]
Can you expand on your plan? Do you want to have a list of `shorthand` properties and use that while sorting?

**Comment by Siilwyn** [comment]
Okay you would have to create a structure that contains the relation between those properties then. Looking forward to your idea. :)

For now I've put the order as a function in a branch so you can try it out with `npm i siilwyn/css-declaration-sorter#sortorder-function`

**Comment by evilebottnawi** [comment]
@Siilwyn Thanks :+1:
