### ISSUE TITLE
Add an example to set the order in CLI

### ISSUE THREAD

**Issue by lcoenen** [Siilwyn/css-declaration-sorter#67]
Hi

It's so simple I'm ashamed of asking here, but could we add an example on how to set the order variable using the CLI?

I tried `--order`, but it's not working.

Any idea?

**Comment by Siilwyn** [comment]
Hi, no problem!

As stated [here](https://github.com/postcss/postcss-cli#config) to pass options to plugins a configuration file is needed.

For example using `postcss.config.js`:
```js
module.exports = {
  plugins: [
    require('css-declaration-sorter')({ order: 'concentric-css' }),
  ]
}
```

**Comment by RodrigoTomeES** [comment]
I have made a pull request with two more examples that use order, sass syntax and custom directory to sort all files.
