### ISSUE TITLE
Sort scss with gulp 

### ISSUE THREAD

**Issue by Unknow-max** [Siilwyn/css-declaration-sorter#82]
Hi!
First of all, thank you for your Great work on this plugin.
I have a question, in the readme we can find how to use the plugin with gulp:
```js
const gulp = require('gulp');
const gulpPostcss = require('gulp-postcss');
const cssDeclarationSorter = require('css-declaration-sorter');

gulp.task('css', function () {
  return gulp.src('some.css')
    .pipe(gulpPostcss([cssDeclarationSorter({order: 'smacss'})]))
    .pipe(gulp.dest('./'));
});
```
But, if I want to sort scss declarations, how I can do that? I already know that I Need to install post scss plugin parser, but then how can I implement It? I cannot find something useful in the documentation.

Thank you for reading

**Comment by Unknow-max** [comment]
Oh! Nothing, I solved the problem by myself! All I had to to was to install postcss-scss package 😅

**Comment by Siilwyn** [comment]
Thank you!

This should work, passing the `postcss-scss` in the options object of postcss:

```js
const gulp = require('gulp');
const gulpPostcss = require('gulp-postcss');
const cssDeclarationSorter = require('css-declaration-sorter');
const postcssScssSyntax = require('postcss-scss');

gulp.task('css', function () {
  return gulp.src('some.css')
    .pipe(gulpPostcss(
        [cssDeclarationSorter({order: 'smacss'})],
        { syntax: postcssScssSyntax }
    ))
    .pipe(gulp.dest('./'));
});
```
